### ISSUE TITLE
Can't reproduce examples from netref docu

### ISSUE THREAD

**Issue by constron2** [tomerfiliba-org/rpyc#390] opened 2020-07-07 08:17 UTC
Hi there, 

When running the examples from netref tutorial (https://rpyc.readthedocs.io/en/latest/tutorial/tut2.html) I don't get the same results.
Could you please clarify the expected behaviour? 
If you are interested I could add some doctests to the sphinx documentation. I just don't know the proper way to run them yet.

##### Environment

- rpyc version: 4.1.5
- python version: 3.6.8
- operating system: Ubuntu 18.04

##### Minimal example

Server:

```python
from rpyc.utils.zerodeploy import DeployedServer
from plumbum import SshMachine

machine = SshMachine("127.0.0.1")
server = DeployedServer(machine)
conn = server.classic_connect()
print(f"type(conn.modules.sys): {type(conn.modules.sys)}, in docu: <netref class 'builtins.module'>")
print(f"type(conn.modules.sys.path): {type(conn.modules.sys.path)}, in docu: <netref class 'builtins.list'>")
print(f"type(conn.modules.os.path.abspath): {type(conn.modules.os.path.abspath)}, in docu: <netref class 'builtins.function'>")

print(f"isinstance(conn.modules.sys.path, list): {isinstance(conn.modules.sys.path, list)}, in docu: True")

import inspect
print(f"inspect.isbuiltin(conn.modules.os.listdir): {inspect.isbuiltin(conn.modules.os.listdir)}, in docu: True")
print(f"inspect.isbuiltin(conn.modules.os.path.abspath): {inspect.isfunction(conn.modules.os.path.abspath)}, in docu: True")
print(f"inspect.ismethod(conn.modules.os.path.abspath): {inspect.ismethod(conn.modules.os.path.abspath)}, in docu: False")
print(f"inspect.ismethod(conn.modules.sys.stdout.write): {inspect.ismethod(conn.modules.sys.stdout.write)}, in docu: True")
```
Results: 

type(conn.modules.sys): <netref class 'rpyc.core.netref.sys'>, in docu: <netref class 'builtins.module'>

type(conn.modules.sys.path): <netref class 'rpyc.core.netref.type'>, in docu: <netref class 'builtins.list'>

type(conn.modules.os.path.abspath): <netref class 'rpyc.core.netref.builtins.function'>, in docu: <netref class 'builtins.function'>

isinstance(conn.modules.sys.path, list): True, in docu: True

inspect.isbuiltin(conn.modules.os.listdir): **False, in docu: True**

inspect.isbuiltin(conn.modules.os.path.abspath): **False, in docu: True**

inspect.ismethod(conn.modules.os.path.abspath): False, in docu: False

inspect.ismethod(conn.modules.sys.stdout.write): **False, in docu: True**

**Comment by comrumino** [comment] 2021-03-22 04:33
Duplicate of #355

Thank you for reporting to help provide more test cases

**Closed by comrumino** 2021-03-22 04:33 UTC
Labels: To Start
