### ISSUE TITLE
rpyc execution failed with EOFError: stream has been closed

### ISSUE THREAD

**Issue by kaphola** [tomerfiliba-org/rpyc#424] opened 2020-12-22 07:01 UTC
**Steps**

1. Started communicating to two ubuntu 16 machine parallelly (Executing some set of functions in thread)

**Observation**
Execution is failing with  **EOFError: stream has been closed**. Detailed trace is given below:
```
c:\python37\lib\site-packages\rpyc\core\stream.py:247: in read
    buf = self.sock.recv(min(self.MAX_IO_CHUNK, count))
E   ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

During handling of the above exception, another exception occurred:
```
lib\utils.py:105: in execute_remote_command
    output = eval("launch_command_remote({})".format(kwargs))
<string>:1: in <module>
    ???
c:\python37\lib\site-packages\rpyc\core\netref.py:247: in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
c:\python37\lib\site-packages\rpyc\core\netref.py:76: in syncreq
    return conn.sync_request(handler, proxy, *args)
c:\python37\lib\site-packages\rpyc\core\protocol.py:458: in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
c:\python37\lib\site-packages\rpyc\core\async_.py:100: in value
    self.wait()
c:\python37\lib\site-packages\rpyc\core\async_.py:47: in wait
    self._conn.serve(self._ttl)
c:\python37\lib\site-packages\rpyc\core\protocol.py:377: in serve
    data = self._channel.poll(timeout) and self._channel.recv()
c:\python37\lib\site-packages\rpyc\core\channel.py:55: in recv
    header = self.stream.read(self.FRAME_HEADER.size)
c:\python37\lib\site-packages\rpyc\core\stream.py:257: in read
    raise EOFError(ex)
E   EOFError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

During handling of the above exception, another exception occurred:
```
testcases\conftest.py:150: in InfraSetup
    location_type
steps\nas_steps.py:783: in activate_nas_proxies
    activation_token, build_path, location_type)
steps\nas_steps.py:721: in _check_connection_and_activate_nas_proxy
    nas_device_ip, share_location, agent_name, activation_token)
steps\nas_steps.py:750: in _activate_nas_proxy
    activation_token=activation_token)
lib\utils.py:116: in execute_remote_command
    output = eval("launch_command_remote({})".format(kwargs))
c:\python37\lib\site-packages\rpyc\core\netref.py:247: in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
c:\python37\lib\site-packages\rpyc\core\netref.py:76: in syncreq
    return conn.sync_request(handler, proxy, *args)
c:\python37\lib\site-packages\rpyc\core\protocol.py:458: in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
c:\python37\lib\site-packages\rpyc\core\protocol.py:479: in async_request
    self._async_request(handler, args, res)
c:\python37\lib\site-packages\rpyc\core\protocol.py:464: in _async_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
c:\python37\lib\site-packages\rpyc\core\protocol.py:259: in _send
    self._channel.send(data)
c:\python37\lib\site-packages\rpyc\core\channel.py:75: in send
    self.stream.write(buf)
c:\python37\lib\site-packages\rpyc\core\stream.py:268: in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
c:\python37\lib\site-packages\rpyc\core\stream.py:94: in __getattr__
    raise EOFError("stream has been closed")
E   EOFError: stream has been closed
```

**Environment**

- rpyc version:  rpyc==4.1.1
- python version: Python 3.7.4
- operating system (Client): Windows Server 2012
- operating system (server): Ubuntu16

**Example**

Client Connection:
```
def execute_remote_command(**kwargs):
    """Function to execute methods on remote machine or in local
    Usage:
    utils.execute_remote_command(
        host_ip=<Remote machine ip>, # Do not provide if want to run in local
        f_name=client_utils.create_new_file_with_size, #Function name
        path=file_name_create_path #Arguments
    )
    """
    host_ip = kwargs.get("host_ip", "127.0.0.1")
    port = kwargs.get("port", 18812)
    conn = rpyc.classic.connect(host_ip, port)
    conn._config['sync_request_timeout'] = None
    rpyc.core.stream.SocketStream.MAX_IO_CHUNK = 2000000    
    logger.info("Connection established with host {} at port {}".format(host_ip, port))
    conn.execute("from rpyc_classic import *")
    f_name = kwargs["f_name"]
    kwargs.pop("f_name")
    if "host_ip" in list(kwargs.keys()):
        kwargs.pop("host_ip")
   #To teleport function at server 
    teleport_supported_functions(conn)
    launch_command_remote = teleport_function(conn, f_name)
    logger.info("Executing remote method {}".format(f_name))
    if not kwargs:
        output = eval("launch_command_remote()")
    else:
        output = eval("launch_command_remote({})".format(kwargs))
    conn.close()
    return output
```

**Comment by comrumino** [comment] 2020-12-26 06:35
I confirmed that this issue occurs. More likely than not it is a duplicate of #387.

**Closed by comrumino** 2020-12-26 06:35 UTC
Labels: To Start

**Comment by Craig3TCE** [comment] 2021-01-08 18:26
@comrumino I've been having what I believe to be the same issue as OP. I've updated to the latest release from rpyc.readthedocs.io but am still having the same issue. Does RTD have this fix included or do I need to get it from GH? Thanks :)

**Comment by comrumino** [comment] 2021-01-10 01:18
> @comrumino I've been having what I believe to be the same issue as OP. I've updated to the latest release from rpyc.readthedocs.io but am still having the same issue. Does RTD have this fix included or do I need to get it from GH? Thanks :)

The occurrence of an `EOFError` exception is typically an indication of a design problem in the client or server. If there is an issue with the underlying RPyC protocol or improvement, the GH issue should be more precise. This error is thrown when a stream has been closed but a client or server attempts to access the closed file.

If you attempting to thread, then `EOFError` exceptions will be thrown when you do not synchronize your client-server. Feel free to open a new issue with a more exact client **and** server examples.
