### ISSUE TITLE
Serializing returned dict doesn't work

### ISSUE THREAD

**Issue by liad-guardicore** [tomerfiliba-org/rpyc#393] opened 2020-07-14 07:22 UTC
Describe the issue briefly here, including:

Serializing returned dict fails, rather than being serialized as if it was a regular dict, the object proxying prevents it from being serialized

I don't know if this is necessarily a bug, but I think a flag to disable object proxying (as in pass by-value) for types like dict and such would be very useful.

```
~/temp » python3.7 client.py
Traceback (most recent call last):
  File "client.py", line 7, in <module>
    print(json.dumps(res))
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict is not JSON serializable
```

##### Environment

- rpyc version 4.1.4
- python version 3.7
- operating system Ubuntu

##### Minimal example

Server:

```python
import rpyc
from rpyc.utils.server import OneShotServer

class HelloService(rpyc.Service):
    def exposed_func(self):
        return {"asd": "aaa"}


if __name__ == "__main__":
    rpyc.lib.setup_logger()
    server = OneShotServer(HelloService, port=12345, protocol_config={'allow_pickle': True, 'allow_all_attrs': True})
    server.start()
```

Client:

```python
import rpyc
import json

if __name__ == "__main__":
    c = rpyc.connect("localhost", 12345, config={'allow_pickle': False, 'allow_all_attrs': True})
    res = c.root.exposed_func()
    print(json.dumps(res))
```

**Comment by Jongy** [comment] 2020-07-23 09:12
Such a flag would indeed be useful.

By the way, this specific problem (with `json.dumps`) can be bypassed by passing any of the "special" parameters `dumps` accepts (e.g `indent`, `ensure_ascii`, ...) because they prevent `dumps` from using the JSON encoder implemented in C (which doesn't support `dict` subclasses such as `rpyc.core.netref.builtins.dict`). Instead it falls back to the `JSONEncoder` class in Python, which handles `dict` subclasses.

**Comment by liad-guardicore** [comment] 2020-07-23 10:14
> Such a flag would indeed be useful.
> 
> By the way, this specific problem (with `json.dumps`) can be bypassed by passing any of the "special" parameters `dumps` accepts (e.g `indent`, `ensure_ascii`, ...) because they prevent `dumps` from using the JSON encoder implemented in C (which doesn't support `dict` subclasses such as `rpyc.core.netref.builtins.dict`). Instead it falls back to the `JSONEncoder` class in Python, which handles `dict` subclasses.

Hey @Jongy , thanks for the reply, I found several workarounds for this, though most of the cases I encountered this wasn't with `json.dumps` but with other things (e.g. wrapping `elasticsearch` module and `pymongo` module with RPyC), I used `json.dumps` just to demonstrate the issue.

**Comment by Jongy** [comment] 2020-07-23 10:25
I see. A more generic solution (that'll apply to other builtins as well) is to reconstruct the object: `dict(x)` returns a local dict, whether `x` is a `dict` or `rpyc.core.netref.builtins.dict`.

**Comment by liad-guardicore** [comment] 2020-07-23 11:27
> I see. A more generic solution (that'll apply to other builtins as well) is to reconstruct the object: `dict(x)` returns a local dict, whether `x` is a `dict` or `rpyc.core.netref.builtins.dict`.

Yup, that is what I did in most cases, though it does require me to enable public attributes which isn't optimal, and in some edge cases this is not possible if I expose a function without wrapping it (which tends to happen when exposing public attributes).

Having a "by_val" flag would seem to be the best solution for my case.

**Comment by comrumino** [comment] 2022-10-31 03:09
RPyC has a hard time being transparent when the client starts using CPython. You could expose the json module on the remote host. Alternatively, update the client side to do something similar to below.
```
import rpyc
import json

if __name__ == "__main__":
    c = rpyc.connect("localhost", 12345, config={'allow_pickle': False, 'allow_all_attrs': True})
    res = c.root.exposed_func()
    print(json.dumps(rpyc.classic.obtain(res)))
```
I think improving the usability around pickling/serialization is a fair take away. I'm closing this issue as a duplicate of #350

**Closed by comrumino** 2022-10-31 03:09 UTC
Labels: To Start
